import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
    {
        ignores: [
            '**/dist/**',
            '**/node_modules/**',
            '_blocks/**',
            'coverage/**',
            // Generated by the fixture-generator CLI.
            'fixtures/**',
            // Only TypeScript sources are linted; .js/.cjs/.mjs files are
            // tool configs (jest, babel, the jest preset) with little to lint.
            '**/*.js',
            '**/*.cjs',
            '**/*.mjs',
        ],
    },
    eslint.configs.recommended,
    ...tseslint.configs.recommended,
    {
        files: ['**/*.{ts,tsx}'],
        rules: {
            // The testing library deliberately types runtime-loaded SDK
            // internals and SDK model surfaces as `any` (see
            // packages/testing/src/sdk_internals.ts and CLAUDE.md).
            '@typescript-eslint/no-explicit-any': 'off',
            '@typescript-eslint/no-unused-vars': [
                'error',
                {argsIgnorePattern: '^_', varsIgnorePattern: '^_'},
            ],
        },
    },
    {
        // Test files use jest globals and occasional require() (dist smoke).
        files: ['**/test/**/*.{ts,tsx}'],
        rules: {
            '@typescript-eslint/no-require-imports': 'off',
        },
        languageOptions: {
            globals: {
                describe: 'readonly',
                it: 'readonly',
                test: 'readonly',
                expect: 'readonly',
                beforeEach: 'readonly',
                afterEach: 'readonly',
                beforeAll: 'readonly',
                afterAll: 'readonly',
                jest: 'readonly',
                require: 'readonly',
            },
        },
    },
);
