// Generated by airtable-testing-fixtures. Re-run the CLI to refresh.
import {type FixtureData} from '@usdr/airtable-interface-testing';

export const fixtureData: FixtureData = {
    "base": {
        "id": "appTestFixtureSam",
        "name": "Test fixture sample",
        "collaborators": [
            {
                "id": "usrtestdriver0000",
                "name": "Test User",
                "email": "test.user@example.com",
                "isActive": true
            },
            {
                "id": "usrPatChen0000000",
                "name": "Pat Chen",
                "email": "pat.chen@example.com",
                "isActive": true
            }
        ],
        "tables": [
            {
                "id": "tblTasks",
                "name": "Tasks",
                "description": "Sample data for the todo-list interface extension test suite (airtable-interface-extension-testing repo)",
                "fields": [
                    {
                        "id": "fldName",
                        "name": "Name",
                        "description": null,
                        "type": "singleLineText",
                        "options": null
                    },
                    {
                        "id": "fldNotes",
                        "name": "Notes",
                        "description": null,
                        "type": "multilineText",
                        "options": null
                    },
                    {
                        "id": "fldAssignee",
                        "name": "Assignee",
                        "description": null,
                        "type": "singleCollaborator",
                        "options": null
                    },
                    {
                        "id": "fldStatus",
                        "name": "Status",
                        "description": null,
                        "type": "singleSelect",
                        "options": {
                            "choices": [
                                {
                                    "id": "selTodo",
                                    "name": "Todo",
                                    "color": "redLight2"
                                },
                                {
                                    "id": "selInProgress",
                                    "name": "In progress",
                                    "color": "yellowLight2"
                                },
                                {
                                    "id": "selDone",
                                    "name": "Done",
                                    "color": "greenLight2"
                                }
                            ]
                        }
                    },
                    {
                        "id": "fldAttachments",
                        "name": "Attachments",
                        "description": null,
                        "type": "multipleAttachments",
                        "options": {
                            "isReversed": false
                        }
                    },
                    {
                        "id": "fldDone",
                        "name": "Done",
                        "description": "Checkbox field targeted by the extension's doneField custom property",
                        "type": "checkbox",
                        "options": {
                            "icon": "check",
                            "color": "greenBright"
                        }
                    },
                    {
                        "id": "fldFieldTesting",
                        "name": "Field testing",
                        "description": null,
                        "type": "multipleRecordLinks",
                        "options": {
                            "linkedTableId": "tblFieldTesting",
                            "isReversed": false,
                            "prefersSingleRecordLink": false,
                            "inverseLinkFieldId": "fldLinkToTasks"
                        }
                    }
                ],
                "records": [
                    {
                        "id": "recDoLaundry",
                        "createdTime": "2026-08-01T11:12:03.000Z",
                        "cellValuesByFieldId": {
                            "fldName": "Do laundry",
                            "fldStatus": {
                                "id": "selDone",
                                "name": "Done",
                                "color": "greenLight2"
                            },
                            "fldFieldTesting": [
                                {
                                    "id": "recSampleRow2Edge",
                                    "name": "Sample row 2 — edge values"
                                }
                            ],
                            "fldDone": true
                        }
                    },
                    {
                        "id": "recWaterPlants",
                        "createdTime": "2026-08-01T11:12:03.000Z",
                        "cellValuesByFieldId": {
                            "fldName": "Water plants",
                            "fldStatus": {
                                "id": "selTodo",
                                "name": "Todo",
                                "color": "redLight2"
                            },
                            "fldFieldTesting": [
                                {
                                    "id": "recSampleRow1AllF",
                                    "name": "Sample row 1 — all field types"
                                }
                            ]
                        }
                    },
                    {
                        "id": "recBuyGroceries",
                        "createdTime": "2026-08-01T11:12:03.000Z",
                        "cellValuesByFieldId": {
                            "fldNotes": "Milk, eggs, bread",
                            "fldName": "Buy groceries",
                            "fldStatus": {
                                "id": "selTodo",
                                "name": "Todo",
                                "color": "redLight2"
                            },
                            "fldFieldTesting": [
                                {
                                    "id": "recSampleRow1AllF",
                                    "name": "Sample row 1 — all field types"
                                }
                            ]
                        }
                    }
                ]
            },
            {
                "id": "tblFieldTesting",
                "name": "Field testing",
                "description": "Every creatable Airtable field type and full option permutations, for generating a fixture that mocks all field types. Built via the Airtable connector API (types it cannot create — autoNumber, button, createdTime, lastModifiedTime, createdBy, lastModifiedBy, externalSyncSource, aiText — are not present).",
                "fields": [
                    {
                        "id": "fldName2",
                        "name": "Name",
                        "description": null,
                        "type": "singleLineText",
                        "options": null
                    },
                    {
                        "id": "fldSingleLineText",
                        "name": "Single line text",
                        "description": null,
                        "type": "singleLineText",
                        "options": null
                    },
                    {
                        "id": "fldEmail",
                        "name": "Email",
                        "description": null,
                        "type": "email",
                        "options": null
                    },
                    {
                        "id": "fldURL",
                        "name": "URL",
                        "description": null,
                        "type": "url",
                        "options": null
                    },
                    {
                        "id": "fldMultilineTextL",
                        "name": "Multiline text (long text)",
                        "description": null,
                        "type": "multilineText",
                        "options": null
                    },
                    {
                        "id": "fldRichTextLongTe",
                        "name": "Rich text (long text + rich formatting)",
                        "description": null,
                        "type": "richText",
                        "options": null
                    },
                    {
                        "id": "fldPhoneNumber",
                        "name": "Phone number",
                        "description": null,
                        "type": "phoneNumber",
                        "options": null
                    },
                    {
                        "id": "fldBarcode",
                        "name": "Barcode",
                        "description": null,
                        "type": "barcode",
                        "options": null
                    },
                    {
                        "id": "fldAttachments2",
                        "name": "Attachments",
                        "description": null,
                        "type": "multipleAttachments",
                        "options": {
                            "isReversed": false
                        }
                    },
                    {
                        "id": "fldSingleCollabor",
                        "name": "Single collaborator",
                        "description": null,
                        "type": "singleCollaborator",
                        "options": null
                    },
                    {
                        "id": "fldMultipleCollab",
                        "name": "Multiple collaborators",
                        "description": null,
                        "type": "multipleCollaborators",
                        "options": null
                    },
                    {
                        "id": "fldNumberPrecisio",
                        "name": "Number precision 0",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 0
                        }
                    },
                    {
                        "id": "fldNumberPrecisi2",
                        "name": "Number precision 1",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 1
                        }
                    },
                    {
                        "id": "fldNumberPrecisi3",
                        "name": "Number precision 2",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 2
                        }
                    },
                    {
                        "id": "fldNumberPrecisi4",
                        "name": "Number precision 3",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 3
                        }
                    },
                    {
                        "id": "fldNumberPrecisi5",
                        "name": "Number precision 4",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 4
                        }
                    },
                    {
                        "id": "fldNumberPrecisi6",
                        "name": "Number precision 5",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 5
                        }
                    },
                    {
                        "id": "fldNumberPrecisi7",
                        "name": "Number precision 6",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 6
                        }
                    },
                    {
                        "id": "fldNumberPrecisi8",
                        "name": "Number precision 7",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 7
                        }
                    },
                    {
                        "id": "fldNumberPrecisi9",
                        "name": "Number precision 8",
                        "description": null,
                        "type": "number",
                        "options": {
                            "precision": 8
                        }
                    },
                    {
                        "id": "fldPercentPrecisi",
                        "name": "Percent precision 0",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 0
                        }
                    },
                    {
                        "id": "fldPercentPrecis2",
                        "name": "Percent precision 1",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 1
                        }
                    },
                    {
                        "id": "fldPercentPrecis3",
                        "name": "Percent precision 2",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 2
                        }
                    },
                    {
                        "id": "fldPercentPrecis4",
                        "name": "Percent precision 3",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 3
                        }
                    },
                    {
                        "id": "fldPercentPrecis5",
                        "name": "Percent precision 4",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 4
                        }
                    },
                    {
                        "id": "fldPercentPrecis6",
                        "name": "Percent precision 5",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 5
                        }
                    },
                    {
                        "id": "fldPercentPrecis7",
                        "name": "Percent precision 6",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 6
                        }
                    },
                    {
                        "id": "fldPercentPrecis8",
                        "name": "Percent precision 7",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 7
                        }
                    },
                    {
                        "id": "fldPercentPrecis9",
                        "name": "Percent precision 8",
                        "description": null,
                        "type": "percent",
                        "options": {
                            "precision": 8
                        }
                    },
                    {
                        "id": "fldCurrencyPrecis",
                        "name": "Currency $ precision 0",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 0,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyPreci2",
                        "name": "Currency $ precision 1",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 1,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyPreci3",
                        "name": "Currency $ precision 2",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 2,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyPreci4",
                        "name": "Currency $ precision 3",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 3,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyPreci5",
                        "name": "Currency $ precision 4",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 4,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyPreci6",
                        "name": "Currency $ precision 5",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 5,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyPreci7",
                        "name": "Currency $ precision 6",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 6,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyPreci8",
                        "name": "Currency $ precision 7",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 7,
                            "symbol": "$"
                        }
                    },
                    {
                        "id": "fldCurrencyEURPre",
                        "name": "Currency EUR precision 2",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 2,
                            "symbol": "€"
                        }
                    },
                    {
                        "id": "fldCurrencyGBPPre",
                        "name": "Currency GBP precision 2",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 2,
                            "symbol": "£"
                        }
                    },
                    {
                        "id": "fldCurrencyJPYPre",
                        "name": "Currency JPY precision 0",
                        "description": null,
                        "type": "currency",
                        "options": {
                            "precision": 0,
                            "symbol": "¥"
                        }
                    },
                    {
                        "id": "fldDurationHMm",
                        "name": "Duration h:mm",
                        "description": null,
                        "type": "duration",
                        "options": {
                            "durationFormat": "h:mm"
                        }
                    },
                    {
                        "id": "fldDurationHMmSs",
                        "name": "Duration h:mm:ss",
                        "description": null,
                        "type": "duration",
                        "options": {
                            "durationFormat": "h:mm:ss"
                        }
                    },
                    {
                        "id": "fldDurationHMmSsS",
                        "name": "Duration h:mm:ss.S",
                        "description": null,
                        "type": "duration",
                        "options": {
                            "durationFormat": "h:mm:ss.S"
                        }
                    },
                    {
                        "id": "fldDurationHMmSs2",
                        "name": "Duration h:mm:ss.SS",
                        "description": null,
                        "type": "duration",
                        "options": {
                            "durationFormat": "h:mm:ss.SS"
                        }
                    },
                    {
                        "id": "fldDurationHMmSs3",
                        "name": "Duration h:mm:ss.SSS",
                        "description": null,
                        "type": "duration",
                        "options": {
                            "durationFormat": "h:mm:ss.SSS"
                        }
                    },
                    {
                        "id": "fldDateLocal",
                        "name": "Date local",
                        "description": null,
                        "type": "date",
                        "options": {
                            "dateFormat": {
                                "name": "local",
                                "format": "l"
                            }
                        }
                    },
                    {
                        "id": "fldDateFriendly",
                        "name": "Date friendly",
                        "description": null,
                        "type": "date",
                        "options": {
                            "dateFormat": {
                                "name": "friendly",
                                "format": "LL"
                            }
                        }
                    },
                    {
                        "id": "fldDateUs",
                        "name": "Date us",
                        "description": null,
                        "type": "date",
                        "options": {
                            "dateFormat": {
                                "name": "us",
                                "format": "M/D/YYYY"
                            }
                        }
                    },
                    {
                        "id": "fldDateEuropean",
                        "name": "Date european",
                        "description": null,
                        "type": "date",
                        "options": {
                            "dateFormat": {
                                "name": "european",
                                "format": "D/M/YYYY"
                            }
                        }
                    },
                    {
                        "id": "fldDateIso",
                        "name": "Date iso",
                        "description": null,
                        "type": "date",
                        "options": {
                            "dateFormat": {
                                "name": "iso",
                                "format": "YYYY-MM-DD"
                            }
                        }
                    },
                    {
                        "id": "fldDateTimeLocal1",
                        "name": "DateTime local 12hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "local",
                                "format": "l"
                            },
                            "timeFormat": {
                                "name": "12hour",
                                "format": "h:mma"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeLocal2",
                        "name": "DateTime local 24hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "local",
                                "format": "l"
                            },
                            "timeFormat": {
                                "name": "24hour",
                                "format": "HH:mm"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeFriend",
                        "name": "DateTime friendly 12hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "friendly",
                                "format": "LL"
                            },
                            "timeFormat": {
                                "name": "12hour",
                                "format": "h:mma"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeFrien2",
                        "name": "DateTime friendly 24hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "friendly",
                                "format": "LL"
                            },
                            "timeFormat": {
                                "name": "24hour",
                                "format": "HH:mm"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeUs12ho",
                        "name": "DateTime us 12hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "us",
                                "format": "M/D/YYYY"
                            },
                            "timeFormat": {
                                "name": "12hour",
                                "format": "h:mma"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeUs24ho",
                        "name": "DateTime us 24hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "us",
                                "format": "M/D/YYYY"
                            },
                            "timeFormat": {
                                "name": "24hour",
                                "format": "HH:mm"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeEurope",
                        "name": "DateTime european 12hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "european",
                                "format": "D/M/YYYY"
                            },
                            "timeFormat": {
                                "name": "12hour",
                                "format": "h:mma"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeEurop2",
                        "name": "DateTime european 24hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "european",
                                "format": "D/M/YYYY"
                            },
                            "timeFormat": {
                                "name": "24hour",
                                "format": "HH:mm"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeIso12h",
                        "name": "DateTime iso 12hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "iso",
                                "format": "YYYY-MM-DD"
                            },
                            "timeFormat": {
                                "name": "12hour",
                                "format": "h:mma"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeIso24h",
                        "name": "DateTime iso 24hour UTC",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "iso",
                                "format": "YYYY-MM-DD"
                            },
                            "timeFormat": {
                                "name": "24hour",
                                "format": "HH:mm"
                            },
                            "timeZone": "utc"
                        }
                    },
                    {
                        "id": "fldDateTimeIso242",
                        "name": "DateTime iso 24hour America/New_York",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "iso",
                                "format": "YYYY-MM-DD"
                            },
                            "timeFormat": {
                                "name": "24hour",
                                "format": "HH:mm"
                            },
                            "timeZone": "America/New_York"
                        }
                    },
                    {
                        "id": "fldDateTimeUs12h2",
                        "name": "DateTime us 12hour Europe/London",
                        "description": null,
                        "type": "dateTime",
                        "options": {
                            "dateFormat": {
                                "name": "us",
                                "format": "M/D/YYYY"
                            },
                            "timeFormat": {
                                "name": "12hour",
                                "format": "h:mma"
                            },
                            "timeZone": "Europe/London"
                        }
                    },
                    {
                        "id": "fldSingleSelectAl",
                        "name": "Single select (all colors)",
                        "description": null,
                        "type": "singleSelect",
                        "options": {
                            "choices": [
                                {
                                    "id": "selBlueLight2",
                                    "name": "blueLight2",
                                    "color": "blueLight2"
                                },
                                {
                                    "id": "selCyanLight2",
                                    "name": "cyanLight2",
                                    "color": "cyanLight2"
                                },
                                {
                                    "id": "selTealLight2",
                                    "name": "tealLight2",
                                    "color": "tealLight2"
                                },
                                {
                                    "id": "selGreenLight2",
                                    "name": "greenLight2",
                                    "color": "greenLight2"
                                },
                                {
                                    "id": "selYellowLight2",
                                    "name": "yellowLight2",
                                    "color": "yellowLight2"
                                },
                                {
                                    "id": "selOrangeLight2",
                                    "name": "orangeLight2",
                                    "color": "orangeLight2"
                                },
                                {
                                    "id": "selRedLight2",
                                    "name": "redLight2",
                                    "color": "redLight2"
                                },
                                {
                                    "id": "selPinkLight2",
                                    "name": "pinkLight2",
                                    "color": "pinkLight2"
                                },
                                {
                                    "id": "selPurpleLight2",
                                    "name": "purpleLight2",
                                    "color": "purpleLight2"
                                },
                                {
                                    "id": "selGrayLight2",
                                    "name": "grayLight2",
                                    "color": "grayLight2"
                                },
                                {
                                    "id": "selBlueLight1",
                                    "name": "blueLight1",
                                    "color": "blueLight1"
                                },
                                {
                                    "id": "selCyanLight1",
                                    "name": "cyanLight1",
                                    "color": "cyanLight1"
                                },
                                {
                                    "id": "selTealLight1",
                                    "name": "tealLight1",
                                    "color": "tealLight1"
                                },
                                {
                                    "id": "selGreenLight1",
                                    "name": "greenLight1",
                                    "color": "greenLight1"
                                },
                                {
                                    "id": "selYellowLight1",
                                    "name": "yellowLight1",
                                    "color": "yellowLight1"
                                },
                                {
                                    "id": "selOrangeLight1",
                                    "name": "orangeLight1",
                                    "color": "orangeLight1"
                                },
                                {
                                    "id": "selRedLight1",
                                    "name": "redLight1",
                                    "color": "redLight1"
                                },
                                {
                                    "id": "selPinkLight1",
                                    "name": "pinkLight1",
                                    "color": "pinkLight1"
                                },
                                {
                                    "id": "selPurpleLight1",
                                    "name": "purpleLight1",
                                    "color": "purpleLight1"
                                },
                                {
                                    "id": "selGrayLight1",
                                    "name": "grayLight1",
                                    "color": "grayLight1"
                                },
                                {
                                    "id": "selBlueBright",
                                    "name": "blueBright",
                                    "color": "blueBright"
                                },
                                {
                                    "id": "selCyanBright",
                                    "name": "cyanBright",
                                    "color": "cyanBright"
                                },
                                {
                                    "id": "selTealBright",
                                    "name": "tealBright",
                                    "color": "tealBright"
                                },
                                {
                                    "id": "selGreenBright",
                                    "name": "greenBright",
                                    "color": "greenBright"
                                },
                                {
                                    "id": "selYellowBright",
                                    "name": "yellowBright",
                                    "color": "yellowBright"
                                },
                                {
                                    "id": "selOrangeBright",
                                    "name": "orangeBright",
                                    "color": "orangeBright"
                                },
                                {
                                    "id": "selRedBright",
                                    "name": "redBright",
                                    "color": "redBright"
                                },
                                {
                                    "id": "selPinkBright",
                                    "name": "pinkBright",
                                    "color": "pinkBright"
                                },
                                {
                                    "id": "selPurpleBright",
                                    "name": "purpleBright",
                                    "color": "purpleBright"
                                },
                                {
                                    "id": "selGrayBright",
                                    "name": "grayBright",
                                    "color": "grayBright"
                                },
                                {
                                    "id": "selBlueDark1",
                                    "name": "blueDark1",
                                    "color": "blueDark1"
                                },
                                {
                                    "id": "selCyanDark1",
                                    "name": "cyanDark1",
                                    "color": "cyanDark1"
                                },
                                {
                                    "id": "selTealDark1",
                                    "name": "tealDark1",
                                    "color": "tealDark1"
                                },
                                {
                                    "id": "selGreenDark1",
                                    "name": "greenDark1",
                                    "color": "greenDark1"
                                },
                                {
                                    "id": "selYellowDark1",
                                    "name": "yellowDark1",
                                    "color": "yellowDark1"
                                },
                                {
                                    "id": "selOrangeDark1",
                                    "name": "orangeDark1",
                                    "color": "orangeDark1"
                                },
                                {
                                    "id": "selRedDark1",
                                    "name": "redDark1",
                                    "color": "redDark1"
                                },
                                {
                                    "id": "selPinkDark1",
                                    "name": "pinkDark1",
                                    "color": "pinkDark1"
                                },
                                {
                                    "id": "selPurpleDark1",
                                    "name": "purpleDark1",
                                    "color": "purpleDark1"
                                },
                                {
                                    "id": "selGrayDark1",
                                    "name": "grayDark1",
                                    "color": "grayDark1"
                                }
                            ]
                        }
                    },
                    {
                        "id": "fldMultipleSelect",
                        "name": "Multiple selects (all colors)",
                        "description": null,
                        "type": "multipleSelects",
                        "options": {
                            "choices": [
                                {
                                    "id": "selBlueLight2",
                                    "name": "blueLight2",
                                    "color": "blueLight2"
                                },
                                {
                                    "id": "selCyanLight2",
                                    "name": "cyanLight2",
                                    "color": "cyanLight2"
                                },
                                {
                                    "id": "selTealLight2",
                                    "name": "tealLight2",
                                    "color": "tealLight2"
                                },
                                {
                                    "id": "selGreenLight2",
                                    "name": "greenLight2",
                                    "color": "greenLight2"
                                },
                                {
                                    "id": "selYellowLight2",
                                    "name": "yellowLight2",
                                    "color": "yellowLight2"
                                },
                                {
                                    "id": "selOrangeLight2",
                                    "name": "orangeLight2",
                                    "color": "orangeLight2"
                                },
                                {
                                    "id": "selRedLight2",
                                    "name": "redLight2",
                                    "color": "redLight2"
                                },
                                {
                                    "id": "selPinkLight2",
                                    "name": "pinkLight2",
                                    "color": "pinkLight2"
                                },
                                {
                                    "id": "selPurpleLight2",
                                    "name": "purpleLight2",
                                    "color": "purpleLight2"
                                },
                                {
                                    "id": "selGrayLight2",
                                    "name": "grayLight2",
                                    "color": "grayLight2"
                                },
                                {
                                    "id": "selBlueLight1",
                                    "name": "blueLight1",
                                    "color": "blueLight1"
                                },
                                {
                                    "id": "selCyanLight1",
                                    "name": "cyanLight1",
                                    "color": "cyanLight1"
                                },
                                {
                                    "id": "selTealLight1",
                                    "name": "tealLight1",
                                    "color": "tealLight1"
                                },
                                {
                                    "id": "selGreenLight1",
                                    "name": "greenLight1",
                                    "color": "greenLight1"
                                },
                                {
                                    "id": "selYellowLight1",
                                    "name": "yellowLight1",
                                    "color": "yellowLight1"
                                },
                                {
                                    "id": "selOrangeLight1",
                                    "name": "orangeLight1",
                                    "color": "orangeLight1"
                                },
                                {
                                    "id": "selRedLight1",
                                    "name": "redLight1",
                                    "color": "redLight1"
                                },
                                {
                                    "id": "selPinkLight1",
                                    "name": "pinkLight1",
                                    "color": "pinkLight1"
                                },
                                {
                                    "id": "selPurpleLight1",
                                    "name": "purpleLight1",
                                    "color": "purpleLight1"
                                },
                                {
                                    "id": "selGrayLight1",
                                    "name": "grayLight1",
                                    "color": "grayLight1"
                                },
                                {
                                    "id": "selBlueBright",
                                    "name": "blueBright",
                                    "color": "blueBright"
                                },
                                {
                                    "id": "selCyanBright",
                                    "name": "cyanBright",
                                    "color": "cyanBright"
                                },
                                {
                                    "id": "selTealBright",
                                    "name": "tealBright",
                                    "color": "tealBright"
                                },
                                {
                                    "id": "selGreenBright",
                                    "name": "greenBright",
                                    "color": "greenBright"
                                },
                                {
                                    "id": "selYellowBright",
                                    "name": "yellowBright",
                                    "color": "yellowBright"
                                },
                                {
                                    "id": "selOrangeBright",
                                    "name": "orangeBright",
                                    "color": "orangeBright"
                                },
                                {
                                    "id": "selRedBright",
                                    "name": "redBright",
                                    "color": "redBright"
                                },
                                {
                                    "id": "selPinkBright",
                                    "name": "pinkBright",
                                    "color": "pinkBright"
                                },
                                {
                                    "id": "selPurpleBright",
                                    "name": "purpleBright",
                                    "color": "purpleBright"
                                },
                                {
                                    "id": "selGrayBright",
                                    "name": "grayBright",
                                    "color": "grayBright"
                                },
                                {
                                    "id": "selBlueDark1",
                                    "name": "blueDark1",
                                    "color": "blueDark1"
                                },
                                {
                                    "id": "selCyanDark1",
                                    "name": "cyanDark1",
                                    "color": "cyanDark1"
                                },
                                {
                                    "id": "selTealDark1",
                                    "name": "tealDark1",
                                    "color": "tealDark1"
                                },
                                {
                                    "id": "selGreenDark1",
                                    "name": "greenDark1",
                                    "color": "greenDark1"
                                },
                                {
                                    "id": "selYellowDark1",
                                    "name": "yellowDark1",
                                    "color": "yellowDark1"
                                },
                                {
                                    "id": "selOrangeDark1",
                                    "name": "orangeDark1",
                                    "color": "orangeDark1"
                                },
                                {
                                    "id": "selRedDark1",
                                    "name": "redDark1",
                                    "color": "redDark1"
                                },
                                {
                                    "id": "selPinkDark1",
                                    "name": "pinkDark1",
                                    "color": "pinkDark1"
                                },
                                {
                                    "id": "selPurpleDark1",
                                    "name": "purpleDark1",
                                    "color": "purpleDark1"
                                },
                                {
                                    "id": "selGrayDark1",
                                    "name": "grayDark1",
                                    "color": "grayDark1"
                                }
                            ]
                        }
                    },
                    {
                        "id": "fldCheckbox",
                        "name": "Checkbox",
                        "description": null,
                        "type": "checkbox",
                        "options": {
                            "icon": "check",
                            "color": "greenBright"
                        }
                    },
                    {
                        "id": "fldRating",
                        "name": "Rating",
                        "description": null,
                        "type": "rating",
                        "options": {
                            "icon": "star",
                            "max": 5,
                            "color": "yellowBright"
                        }
                    },
                    {
                        "id": "fldLinkToTasks",
                        "name": "Link to Tasks",
                        "description": null,
                        "type": "multipleRecordLinks",
                        "options": {
                            "linkedTableId": "tblTasks",
                            "isReversed": false,
                            "prefersSingleRecordLink": false,
                            "inverseLinkFieldId": "fldFieldTesting"
                        }
                    },
                    {
                        "id": "fldFormula",
                        "name": "Formula",
                        "description": null,
                        "type": "formula",
                        "options": {
                            "isValid": true,
                            "formula": "CONCATENATE({fldYsVPKCsYjpe0CR}, \" — \", {fldoa49kDgxU9Rltl})",
                            "referencedFieldIds": [
                                "fldYsVPKCsYjpe0CR",
                                "fldoa49kDgxU9Rltl"
                            ],
                            "result": {
                                "type": "singleLineText"
                            }
                        }
                    },
                    {
                        "id": "fldCountOfLinkedT",
                        "name": "Count (of linked Tasks)",
                        "description": null,
                        "type": "count",
                        "options": {
                            "isValid": true,
                            "recordLinkFieldId": "fldpIbvgXOSABybfI"
                        }
                    },
                    {
                        "id": "fldLookupTaskName",
                        "name": "Lookup (Task name)",
                        "description": null,
                        "type": "multipleLookupValues",
                        "options": {
                            "isValid": true,
                            "recordLinkFieldId": "fldpIbvgXOSABybfI",
                            "fieldIdInLinkedTable": "fldNkrgyKkccJ9y9w",
                            "result": {
                                "type": "singleLineText"
                            }
                        }
                    },
                    {
                        "id": "fldRollupTaskName",
                        "name": "Rollup (Task names joined)",
                        "description": null,
                        "type": "rollup",
                        "options": {
                            "isValid": true,
                            "recordLinkFieldId": "fldpIbvgXOSABybfI",
                            "fieldIdInLinkedTable": "fldNkrgyKkccJ9y9w",
                            "referencedFieldIds": [],
                            "result": {
                                "type": "singleLineText"
                            }
                        }
                    }
                ],
                "records": [
                    {
                        "id": "recSampleRow2Edge",
                        "createdTime": "2026-08-01T11:27:30.000Z",
                        "cellValuesByFieldId": {
                            "fldSingleLineText": "Second row",
                            "fldSingleSelectAl": {
                                "id": "selGrayDark1",
                                "name": "grayDark1",
                                "color": "grayDark1"
                            },
                            "fldRollupTaskName": "Do laundry",
                            "fldDurationHMm": 5400,
                            "fldLookupTaskName": [
                                {
                                    "linkedRecordId": "recDoLaundry",
                                    "value": "Do laundry"
                                }
                            ],
                            "fldCountOfLinkedT": 1,
                            "fldMultipleSelect": [
                                {
                                    "id": "selGrayDark1",
                                    "name": "grayDark1",
                                    "color": "grayDark1"
                                }
                            ],
                            "fldPercentPrecis3": 1,
                            "fldRating": 2,
                            "fldCurrencyPreci3": 0,
                            "fldDateIso": "2000-01-01",
                            "fldName2": "Sample row 2 — edge values",
                            "fldDateTimeIso24h": "2000-01-01T00:00:00.000Z",
                            "fldFormula": "Sample row 2 — edge values — -7",
                            "fldNumberPrecisio": -7,
                            "fldLinkToTasks": [
                                {
                                    "id": "recDoLaundry",
                                    "name": "Do laundry"
                                }
                            ]
                        }
                    },
                    {
                        "id": "recSampleRow1AllF",
                        "createdTime": "2026-08-01T11:27:30.000Z",
                        "cellValuesByFieldId": {
                            "fldSingleLineText": "Sample single line text",
                            "fldPercentPrecis2": 0.425,
                            "fldSingleSelectAl": {
                                "id": "selBlueBright",
                                "name": "blueBright",
                                "color": "blueBright"
                            },
                            "fldPercentPrecis7": 0.42424242,
                            "fldRollupTaskName": "Buy groceries, Water plants",
                            "fldAttachments2": [
                                {
                                    "id": "attihiDpq9V96It9d",
                                    "width": 272,
                                    "height": 92,
                                    "url": "https://v5.airtableusercontent.com/v3/u/55/55/1785715200000/kocHYrJWCm8lIL9CfGJQHQ/7JN5PiGFN9Rt95BM-Mp-c0iv3wXmRU8TqBPuwVAqgyZIuZNIEVIVmLhwVk0NFYZkgO3-IXzAMuWsi_ZN-lkJEACqvxm1ODf3ltWzt3wplqVejBq1yI8PSxZ9zsWpz6XMPVTaKi6EJNxpIBZtMdsmrAeYYgexzNCa615GKHD6MvM/RfC1b6SPQEcNuS1bDAGfkV9T0WgAx9LyT09_w73Z6LQ",
                                    "filename": "googlelogo.png",
                                    "size": 5969,
                                    "type": "image/png",
                                    "thumbnails": {
                                        "small": {
                                            "url": "https://v5.airtableusercontent.com/v3/u/55/55/1785715200000/0cO9VksI6HQMylJ77luPBg/BIBfQU_6-wDWcGWhCjoDS80h0xAzhqSF-lRyvaVUFAIUqJfhcRaYiVqx85HhldjfKGrstfVpEZfcSL0UBmGbVwTXWVH5gTIq9Q2xudK8TFpIXhlLqEKAJOkAq5Y9usTmSO6_eiMvFOHQ--b--3EbxA/CAiutCaQryDmw9E3SZzIDcvgV-mbXGiOVUunzIoWn08",
                                            "width": 106,
                                            "height": 36
                                        },
                                        "large": {
                                            "url": "https://v5.airtableusercontent.com/v3/u/55/55/1785715200000/4o-q7iQsZxw8X5o7hlpJ_A/xUwaVv9VfuBICSh6BJIwOR9peHETz45qXR2qExzrbW3kqpIRJaa_wsnvACpKy-MuepqOjjkZ_47npjv9x2hsvt2Z3jMHtqWE73E8tT90Gp3J8C20pguPdQNvPgAfzrXS1ZiuZ96NRssq4SIWC9dutA/ZuT_UcLJy5ZhpjI5GY9sXQhswywYUAayXQBC40KgGEA",
                                            "width": 272,
                                            "height": 92
                                        },
                                        "full": {
                                            "url": "https://v5.airtableusercontent.com/v3/u/55/55/1785715200000/0l1ueKPbaGI7K-_WMUsOKA/r5OfeJqHK5F9jhx_XKDG4ESz7Rm3TGLLgG5EqxjJ0mKkKellR9Cv0PkyjvLe-tISusFsOJoUV3vf5wYoNPXpZDinKpdt0pmorg7FEPfREZPJqAPkY7cBZnNnGafqHSKtGt9gpSo_qWRMWWQEfC_H4A/ZZgzjUgCJCG_J8HA4uUXUQpFj0UlLVBmjExQasqvdRQ",
                                            "width": 272,
                                            "height": 92
                                        }
                                    }
                                }
                            ],
                            "fldDateTimeIso12h": "2026-07-22T10:04:40.000Z",
                            "fldDurationHMmSsS": 3661.5,
                            "fldDateTimeLocal2": "2026-07-22T10:04:40.000Z",
                            "fldCurrencyEURPre": 19.99,
                            "fldCurrencyPreci2": 19.9,
                            "fldNumberPrecisi3": 42.42,
                            "fldDurationHMm": 3660,
                            "fldCurrencyPreci4": 19.999,
                            "fldDateTimeFrien2": "2026-07-22T10:04:40.000Z",
                            "fldLookupTaskName": [
                                {
                                    "linkedRecordId": "recBuyGroceries",
                                    "value": "Buy groceries"
                                },
                                {
                                    "linkedRecordId": "recWaterPlants",
                                    "value": "Water plants"
                                }
                            ],
                            "fldNumberPrecisi9": 42.42424242,
                            "fldPercentPrecisi": 0.42,
                            "fldCountOfLinkedT": 2,
                            "fldNumberPrecisi8": 42.4242425,
                            "fldPercentPrecis8": 0.424242425,
                            "fldCurrencyPrecis": 20,
                            "fldPhoneNumber": "+1 (555) 123-4567",
                            "fldMultilineTextL": "Line 1\nLine 2\nLine 3",
                            "fldDateTimeUs12h2": "2026-07-22T10:04:40.000Z",
                            "fldDateTimeFriend": "2026-07-22T10:04:40.000Z",
                            "fldMultipleSelect": [
                                {
                                    "id": "selBlueBright",
                                    "name": "blueBright",
                                    "color": "blueBright"
                                },
                                {
                                    "id": "selRedBright",
                                    "name": "redBright",
                                    "color": "redBright"
                                },
                                {
                                    "id": "selGreenLight2",
                                    "name": "greenLight2",
                                    "color": "greenLight2"
                                }
                            ],
                            "fldPercentPrecis3": 0.4242,
                            "fldNumberPrecisi5": 42.4242,
                            "fldNumberPrecisi7": 42.424242,
                            "fldPercentPrecis6": 0.4242425,
                            "fldDurationHMmSs2": 3661.55,
                            "fldDurationHMmSs3": 3661.555,
                            "fldPercentPrecis4": 0.42425,
                            "fldRating": 4,
                            "fldDateEuropean": "2026-07-22",
                            "fldCurrencyPreci3": 19.99,
                            "fldDateIso": "2026-07-22",
                            "fldCurrencyPreci6": 19.99999,
                            "fldName2": "Sample row 1 — all field types",
                            "fldSingleCollabor": {
                                "id": "usrtestdriver0000",
                                "email": "test.user@example.com",
                                "name": "Test User"
                            },
                            "fldMultipleCollab": [
                                {
                                    "id": "usrtestdriver0000",
                                    "email": "test.user@example.com",
                                    "name": "Test User"
                                },
                                {
                                    "id": "usrPatChen0000000",
                                    "email": "pat.chen@example.com",
                                    "name": "Pat Chen"
                                }
                            ],
                            "fldDurationHMmSs": 3661,
                            "fldDateTimeIso24h": "2026-07-22T10:04:40.000Z",
                            "fldRichTextLongTe": "**Bold**, _italic_, and a list:\n- one\n- two\n",
                            "fldCurrencyPreci5": 19.9999,
                            "fldDateTimeLocal1": "2026-07-22T10:04:40.000Z",
                            "fldDateTimeEurope": "2026-07-22T10:04:40.000Z",
                            "fldBarcode": {
                                "text": "012345678905"
                            },
                            "fldURL": "https://example.com",
                            "fldDateUs": "2026-07-22",
                            "fldDateTimeUs12ho": "2026-07-22T10:04:40.000Z",
                            "fldDateTimeUs24ho": "2026-07-22T10:04:40.000Z",
                            "fldNumberPrecisi6": 42.42425,
                            "fldFormula": "Sample row 1 — all field types — 42",
                            "fldDateTimeEurop2": "2026-07-22T10:04:40.000Z",
                            "fldNumberPrecisi2": 42.5,
                            "fldNumberPrecisio": 42,
                            "fldPercentPrecis9": 0.42424242425,
                            "fldDateLocal": "2026-07-22",
                            "fldLinkToTasks": [
                                {
                                    "id": "recBuyGroceries",
                                    "name": "Buy groceries"
                                },
                                {
                                    "id": "recWaterPlants",
                                    "name": "Water plants"
                                }
                            ],
                            "fldNumberPrecisi4": 42.425,
                            "fldDateFriendly": "2026-07-22",
                            "fldCurrencyPreci8": 19.9999999,
                            "fldPercentPrecis5": 0.424242,
                            "fldCurrencyJPYPre": 1999,
                            "fldCheckbox": true,
                            "fldCurrencyPreci7": 19.999999,
                            "fldCurrencyGBPPre": 19.99,
                            "fldDateTimeIso242": "2026-07-22T10:04:40.000Z",
                            "fldEmail": "test@example.com"
                        }
                    }
                ]
            }
        ]
    }
};

export default fixtureData;
