// Generated by airtable-testing-fixtures. Re-run the CLI to refresh.
import {type FixtureData} from '@usdr/airtable-interface-testing';

export const fixtureData: FixtureData = {
    "base": {
        "id": "appInterfaceExten",
        "name": "Interface extension test fixture",
        "tables": [
            {
                "id": "tblTasks",
                "name": "Tasks",
                "description": "Sample data for the todo-list interface extension test suite (airtable-interface-extension-testing repo)",
                "fields": [
                    {
                        "id": "fldName",
                        "name": "Name",
                        "description": null,
                        "type": "singleLineText",
                        "options": null
                    },
                    {
                        "id": "fldNotes",
                        "name": "Notes",
                        "description": null,
                        "type": "multilineText",
                        "options": null
                    },
                    {
                        "id": "fldAssignee",
                        "name": "Assignee",
                        "description": null,
                        "type": "singleCollaborator",
                        "options": null
                    },
                    {
                        "id": "fldStatus",
                        "name": "Status",
                        "description": null,
                        "type": "singleSelect",
                        "options": {
                            "choices": [
                                {
                                    "id": "selTodo",
                                    "name": "Todo",
                                    "color": "redLight2"
                                },
                                {
                                    "id": "selInProgress",
                                    "name": "In progress",
                                    "color": "yellowLight2"
                                },
                                {
                                    "id": "selDone",
                                    "name": "Done",
                                    "color": "greenLight2"
                                }
                            ]
                        }
                    },
                    {
                        "id": "fldAttachments",
                        "name": "Attachments",
                        "description": null,
                        "type": "multipleAttachments",
                        "options": {
                            "isReversed": false
                        }
                    },
                    {
                        "id": "fldDone",
                        "name": "Done",
                        "description": "Checkbox field targeted by the extension's doneField custom property",
                        "type": "checkbox",
                        "options": {
                            "icon": "check",
                            "color": "greenBright"
                        }
                    }
                ],
                "records": [
                    {
                        "id": "recBuyGroceries",
                        "createdTime": "2026-07-22T10:04:40.000Z",
                        "cellValuesByFieldId": {
                            "fldName": "Buy groceries",
                            "fldStatus": {
                                "id": "selTodo",
                                "name": "Todo",
                                "color": "redLight2"
                            },
                            "fldNotes": "Milk, eggs, bread"
                        }
                    },
                    {
                        "id": "recDoLaundry",
                        "createdTime": "2026-07-22T10:04:40.000Z",
                        "cellValuesByFieldId": {
                            "fldName": "Do laundry",
                            "fldStatus": {
                                "id": "selDone",
                                "name": "Done",
                                "color": "greenLight2"
                            },
                            "fldDone": true
                        }
                    },
                    {
                        "id": "recWaterPlants",
                        "createdTime": "2026-07-22T10:04:40.000Z",
                        "cellValuesByFieldId": {
                            "fldName": "Water plants",
                            "fldStatus": {
                                "id": "selTodo",
                                "name": "Todo",
                                "color": "redLight2"
                            }
                        }
                    }
                ]
            }
        ]
    }
};

export default fixtureData;
