/**
 * Serialize FixtureData to a file the test suite imports: a typed TypeScript
 * module by default, or plain JSON with `--json`.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import {type FixtureData} from '@usdr/airtable-interface-testing';

export function renderFixtureModule(fixtureData: FixtureData): string {
    const json = JSON.stringify(fixtureData, null, 4);
    return [
        '// Generated by airtable-testing-fixtures. Re-run the CLI to refresh.',
        "import {type FixtureData} from '@usdr/airtable-interface-testing';",
        '',
        `export const fixtureData: FixtureData = ${json};`,
        '',
        'export default fixtureData;',
        '',
    ].join('\n');
}

export function writeFixtureFile(
    fixtureData: FixtureData,
    outPath: string,
    format: 'ts' | 'json',
): void {
    fs.mkdirSync(path.dirname(path.resolve(outPath)), {recursive: true});
    const content =
        format === 'json'
            ? `${JSON.stringify(fixtureData, null, 4)}\n`
            : renderFixtureModule(fixtureData);
    fs.writeFileSync(outPath, content);
}
